# nombre maximal de connexions simultanées
events {
	worker_connections 1024;
}

http {
	# permet de reconnaitre les extensions (HTML, CSS, etc...)
	include /etc/nginx/mime.types;

	server
	{
		# SSL/TLS Configuration
		listen 443 ssl;
		ssl_protocols TLSv1.2 TLSv1.3;
		ssl_certificate /etc/nginx/ssl/nginx.crt;
		ssl_certificate_key /etc/nginx/ssl/nginx.key;

		root /var/www/html;
		server_name dle-fur.42.fr;
		index index.php

		# requete inconnu
		location / {
			try_files $uri $uri/ /index.php?$args;
		}

		# Pour toutes les requetes php
		# renvoyer les requetes php sur le port 9000
		location ~ \.php$ {
			fastcgi_pass wordpress:9000;
			fastcgi_index index.php;
			include /etc/nginx/fastcgi_params;
			fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		}
	}
}