# pool principale
[www]

# PHP sera exécuté avec l’utilisateur www-data
# PHP sera exécuté avec le groupe www-data
user = www-data
group = www-data

# écoute sur le port 9000 pour recevoir les requêtes FastCGI
listen = 9000

# nombre de processus non-fixe
# limite maximale de processus enfants PHP
# au demarrage, creer deux processus
# garde un processus libre en reserve
# ne garde pas plus de 3 processus inutilisés en réserve
pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3

# ne nettoie pas l’environnement. Laisse les variables d’environnement disponibles
clear_env = no
